### ISSUE TITLE
Short usage description?

### ISSUE THREAD

**Issue by rulrok** [darrenferguson/UmbracoAzureSearch#1]
Hello,

could you provide any quick readme/walk-through on how to install this plugin and use it? :)
Does it replace Umbraco's Examine? Or is it a complement to it?

I came here through this post https://www.moriyama.co.uk/about-us/news/blog-the-need-for-archived-content-in-umbraco-and-how-to-do-it/ and I need an archived system on my solution as well. I hope umbraco 8 brings a native solution to this problem.

Thanks

**Comment by garydevenay** [comment]
Created a pull request for basic usage documentation: https://github.com/darrenferguson/UmbracoAzureSearch/pull/4
