### ISSUE TITLE
Continue indexing on errors

### ISSUE THREAD

**Issue by ziachap** [darrenferguson/UmbracoAzureSearch#13]
MoriyamaAzureSearch.controllers.js, line 77
`
if (!response.data.Error && !response.data.Finished) {
                $scope.reindexContentPage(sessionId, page + 1);
            } else if (response.data.Finished) {
                $scope.TypeProcessing = 'media';
                $scope.reindexMediaPage(response.data.SessionId, 1);
            }
`
The Error flag is true if any document fails to be indexed. In this event, indexing stops and the next pages are not indexed. I think that this error should be raised to the user but indexing should continue, otherwise one bad document will prevent anything else from being indexed.

**Comment by darrenferguson** [comment]
Merged here: Thanks!
https://github.com/darrenferguson/UmbracoAzureSearch/commit/afbf54ee7257b02fb7ab5358068a8fb8e3befe2c
