### ISSUE TITLE
Unable to change Standard Umbraco Fields to IsFilterable

### ISSUE THREAD

**Issue by kristianbjensen** [darrenferguson/UmbracoAzureSearch#38]
Hi
I have a issue because i need to change the default umbraco field "Url" to be filterable. Is this in anyway possible? i tried to set set it in AzureSearch.config but this is not possible.
I need to be able to filter on Url field, like if "Url" starts with "/en/" we will only produce english results from the search. As of standard, Moriyama will set the Url property not filterable.

**Comment by darrenferguson** [comment]
You could write an event to add a custom field to the index, which was filterable I guess...

to make the url field filterable we'd need to make a code change

**Comment by kristianbjensen** [comment]
I guess that could be a workaround. Thanks
