### ISSUE TITLE
TreeSearchResult error on Umbraco 7.5.4

### ISSUE THREAD

**Issue by webfletch** [darrenferguson/UmbracoAzureSearch#55]
I am trying to use the latest version of this code (1.3.8.1) on an Umbraco 7.5.4 website which unfortunately cannot be upgraded to a newer version of Umbraco.

The problem I am facing is that it seems some things in Umbraco have changed since the version I am running, therefore, I get errors relating to “TreeSearchResult" In the “BackOfficeAzureSearchApiController.cs” file.

Is there a copy of the original source code available (I know this solution did work on the version of Umbraco I am running because if you install it using the Umbraco package available in the Developer tools then it works), so that I can reference to get it version 1.3.8.1 to work with Umbraco 7.5.4? 

It seems all the versions on github are using the more recent version of the code (that use "TreeSearchResult") and the version that works with the older versions of Umbraco is not on there.

**Comment by darrenferguson** [comment]
Hi - I am afraid that what is in this repository is the history of the source code that I have.

As you've identified I don't think what is in this repo will work with 7.5.x.

Is there a reason you are trying to update the version of the Azure search package you are using?

**Comment by webfletch** [comment]
The reason I am updating is because I have a custom field that is of type "date" and the original package doesn't seem to recognise this "type" when creating the index on the old version.

Also I wanted the source code for you project including in my solution so that I can fully debug what is going on and also make changes as I have quite a complex search query I need to build up that includes "not" filters and order by descending etc.

**Comment by darrenferguson** [comment]
I think this is the last release before we updated the version of Umbraco - so you should be able to branch from here? https://github.com/darrenferguson/UmbracoAzureSearch/releases/tag/Release-1.3.6

**Comment by webfletch** [comment]
That release looks like it still targets Umbraco 7.12.2 and references the "TreeSearchResult" which doesn't exist in Umbraco 7.5.4 (screenshot below).

Just to clarify I have got most of it working, I needed to comment out the "Search" and "GetTreeSearchResultStructure" methods in the "BackOfficeAzureSearchApiController.cs" file which obviously breaks the Umbraco backend search. All the rest of it seems to be compatible but I think how the Umbraco tree is handled was changed on newer versions of Umbraco.

![Capture](https://user-images.githubusercontent.com/55058365/79568957-acccf700-80ae-11ea-9774-db4ef3bcf54f.PNG)

**Comment by darrenferguson** [comment]
Sorry - my bad - this looks like the commit you need to start from:

https://github.com/darrenferguson/UmbracoAzureSearch/commit/eb8ca02938af51665545ecf3076ed95071b6a3cb

![image](https://user-images.githubusercontent.com/2164132/79570316-20700380-80b1-11ea-9bbc-cf8d394415fc.png)

**Comment by webfletch** [comment]
Great thank you, that seems to be the one, I will copy over the code from that commit cheers.
