### ISSUE TITLE
Unpublishing content doesn't update the index

### ISSUE THREAD

**Issue by webfletch** [darrenferguson/UmbracoAzureSearch#57]
I have noticed that unpublishing content doesn't update the index to show it has been "Unpublished", there isn't an "Unpublish" event handler in the following file: CustomApplicationEventHandler.cs

Am I missing something and the unpublishing should be getting handled some other way, or is there a reason that it is set not to update the index when unpublishing? 

Or should I simply add an unpublish event into CustomApplicationEventHandler.cs to get this working?

**Comment by darrenferguson** [comment]
It is probably just a bug/oversight.

**Comment by webfletch** [comment]
Okay thanks, for anyone else that needs this I have just added the following:

```
ContentService.UnPublished += ContentService_UnPublished;

private void ContentService_UnPublished(IPublishingStrategy sender, PublishEventArgs<IContent> e)
{
        var azureSearchServiceClient = AzureSearchContext.Instance.SearchIndexClient;

        foreach (var entity in e.PublishedEntities)
        {
             azureSearchServiceClient.ReIndexContent(entity);
        }
}
```
