### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by doronuziel71** [darrenferguson/UmbracoAzureSearch#8]
Hi,

This package looks very promising, but just wanted to ask if this extension is applicable for production environments that are not hosted on Azure? Is latency an issue here?

Thanks in advance

Doron

**Comment by darrenferguson** [comment]
Hi Doron,

We host almost everything i Azure - so haven't tested for latency.

I assume it'd be quick enough for website search, but depends what your requirements are.

Thanks.
Darren.
